Common:
  SiteCode: 190
  Password:
    Nested:   "VMware1!"
    Physical: "VMware1!"
    VMs: "VMware1!VMware1!"
  DNS: "10.225.0.5"
  BaseNetwork:
    IPv4: '172.18'
    SubnetMask: 24

Target:
  vCenter:                                                                    # Settings used when "vCenter" deployment is chosen (TargetConfig.Deployment == "vCenter")
    FQDN: FQDN                                                                # FQDN - The FQDN to your physical vCenter Server
    User: user@vsphere.local                                                  # User - vCenter Server user account.  We suggest you create a dedicate account for deployments, such as SDDCLab@vsphere.local
    Password: "{{ Common.Password.Physical }}"                                # Password - Password used by User to authenticate to the physical vCenter Server
    vSwitch: SDDCLab_vDS                                                      # vSwitch - Name of the vDS which is automatically provisioned by the playbooks, and where all the Pod Port-Groups are crated
    vSwitchVersion: 6.6.0                                                     # vSwitchVersion - vDS version used for the given vSwitch
    DataCenter: SDDC                                                          # DataCenter - Defines under which DataCenter object the lab Pod's are deployed
    Cluster: Cluster                                                          # Cluster - Defines which vSphere cluster within DataCenter the lab Pod's are deployed
    Datastore: "DataStore"                                                    # Datastore - Defines Which datastore should the nested lab Pod VMs be placed
    PortGroup:                                                                # Various PortGroups used during deployment
      Web: "SEG-Web"                                                          # SEG-Web - PortGroup which the Web Servers will attach to
      App: "SEG-App"                                                          # SEG-App - PortGroup which the App Server will attach to
      DB: "SEG-DB"                                                            # SEG-DB - PortGroup which the DB Server will attach to
  VMs:
    SEG_Web_GW: "{{Common.BaseNetwork.IPv4}}.{{Common.SiteCode + 1}}.1"
    SEG_App_GW: "{{Common.BaseNetwork.IPv4}}.{{Common.SiteCode + 2}}.1"
    SEG_DB_GW: "{{Common.BaseNetwork.IPv4}}.{{Common.SiteCode + 3}}.1"