Common:
  SiteCode: 21                                          # This is the 3rd octec in the IP Address i.e 10.225."21".X based on IPv4 below
  Password:
    Physical: "VMware1!"                                # Password used for the account on line 20
    VMs: "VMware1!VMware1!"                             # Password that will be applied to the root account in each VM
  DNS: "10.225.0.5"                                     # DNS
  BaseNetwork:
    IPv4: '10.225'                                      # IP's used for Apps i.e ."10.225"
    SubnetMask: 24                                      #

Target:
  vCenter:                                              # Settings used when "vCenter" deployment is chosen (TargetConfig.Deployment == "vCenter")
    FQDN: pod-240-vcenter.sddc.lab                      # FQDN - The FQDN to your physical vCenter Server
    User: administrator@vsphere.local                   # User - vCenter Server user account.  We suggest you create a dedicate account for deployments, such as SDDCLab@vsphere.local
    Password: "{{ Common.Password.Physical }}"          # Password - Password used by User to authenticate to the physical vCenter Server
    DataCenter: Pod-240-DataCenter                      # DataCenter - Defines under which DataCenter object the lab Pod's are deployed
    Cluster: Compute-A                                  # Cluster - Defines which vSphere cluster within DataCenter the lab Pod's are deployed
    Datastore: Compute-A_vSAN                           # Datastore - Defines Which datastore should the nested lab Pod VMs be placed
