Common:
  SiteCode: 20
  Password:
    Nested:   "VMware1!"
    Physical: "VMware1!"
    VMs: "VMware1!VMware1!"
  DNS: "10.225.0.5"
  BaseNetwork:
    IPv4: '10.225'
    SubnetMask: 24

Target:
  vCenter:                                                                    # Settings used when "vCenter" deployment is chosen (TargetConfig.Deployment == "vCenter")
    FQDN: pod-240-vcenter.sddc.lab                                            # FQDN - The FQDN to your physical vCenter Server
    User: administrator@vsphere.local                                               # User - vCenter Server user account.  We suggest you create a dedicate account for deployments, such as SDDCLab@vsphere.local
    Password: "{{ Common.Password.Physical }}"                                # Password - Password used by User to authenticate to the physical vCenter Server
    vSwitch: SDDCLab_vDS                                                      # vSwitch - Name of the vDS which is automatically provisioned by the playbooks, and where all the Pod Port-Groups are crated
    vSwitchVersion: 6.6.0                                                     # vSwitchVersion - vDS version used for the given vSwitch
    DataCenter: Pod-240-DataCenter                                            # DataCenter - Defines under which DataCenter object the lab Pod's are deployed
    Cluster: Compute-A                                                        # Cluster - Defines which vSphere cluster within DataCenter the lab Pod's are deployed
    Datastore: Compute-A_vSAN                                                        # Datastore - Defines Which datastore should the nested lab Pod VMs be placed
