- name: Walk through the setup dialog 1 (Enter 'root' username)
  community.vmware.vmware_guest_sendkey:
    hostname: "{{ Target.vCenter.FQDN }}"
    username: "{{ Target.vCenter.User }}"
    password: "{{ Common.Password.Physical }}" 
    validate_certs: no
    name: "{{ item.name }}"
    string_send: "root"
  
- name: Walk through the setup dialog 2 (Press 'ENTER')
  community.vmware.vmware_guest_sendkey:
    hostname: "{{ Target.vCenter.FQDN }}"
    username: "{{ Target.vCenter.User }}"
    password: "{{ Common.Password.Physical }}" 
    validate_certs: no
    name: "{{ item.name }}"
    keys_send:
      - ENTER 

- name: Walk through the setup dialog 1 (Enter 'current' password)
  community.vmware.vmware_guest_sendkey:
    hostname: "{{ Target.vCenter.FQDN }}"
    username: "{{ Target.vCenter.User }}"
    password: "{{ Common.Password.Physical }}" 
    validate_certs: no
    name: "{{ item.name }}"
    string_send: "VMware1!VMware1!"

- name: Walk through the setup dialog 2 (Press 'ENTER')
  community.vmware.vmware_guest_sendkey:
    hostname: "{{ Target.vCenter.FQDN }}"
    username: "{{ Target.vCenter.User }}"
    password: "{{ Common.Password.Physical }}" 
    validate_certs: no
    name: "{{ item.name }}"
    keys_send:
      - ENTER
