- name: Walk through the setup - Install LSOF
  community.vmware.vmware_guest_sendkey:
    hostname: "{{ Target.vCenter.FQDN }}"
    username: "{{ Target.vCenter.User }}"
    password: "{{ Common.Password.Physical }}"
    validate_certs: no
    name: "{{ item.name }}"
    string_send: "Y"

- name: Walk through the setup dialog 2 (Press 'ENTER')
  community.vmware.vmware_guest_sendkey:
    hostname: "{{ Target.vCenter.FQDN }}"
    username: "{{ Target.vCenter.User }}"
    password: "{{ Common.Password.Physical }}" 
    validate_certs: no
    name: "{{ item.name }}"
    keys_send:
      - ENTER    