---
- hosts: all
  become: no
  gather_facts: False
  connection: local
  tasks:
    - name: Wait for Photon {{ inventory_hostname }} to boot
      ansible.builtin.pause:
        seconds: 140
      run_once: true
