---
- hosts: all
  become: no
  connection: local
  gather_facts: False
  tasks:
    - name: Deploy OVAs for Inventory Using Photon OS
      community.vmware.vmware_deploy_ovf:
        hostname: "{{ Target.vCenter.FQDN }}"
        username: "{{ Target.vCenter.User }}"
        password: "{{ Common.Password.Physical }}" 
        validate_certs: no
        name: "{{ inventory_hostname }}" 
        datacenter: "{{ Target.vCenter.DataCenter }}"
        folder: ""
        cluster: "{{ Target.vCenter.Cluster }}"
        datastore: "{{ Target.vCenter.Datastore }}"
        disk_provisioning: thin
        networks: 
          "None": "{{ PortGroup }}"
        #ova: /Software/VMware/Photon/v1/photon-custom-hw11-1.0-62c543d.ova
        #ova: /Software/VMware/Photon/v2/photon-custom-hw11-2.0-304b817.ova
        ova: /Software/VMware/Photon/v3/photon-hw11-3.0-a383732.ova
        #ova: /Software/VMware/Photon/v4/photon-hw11-4.0-1526e30ba0.ova
        allow_duplicates: no
        power_on: yes
        fail_on_spec_warnings: yes
        wait: no
    - name: Wait for Photon to boot
      ansible.builtin.pause:
        seconds: 140
      run_once: true

