---
- hosts: all
  become: no
  gather_facts: False
  connection: local
  tasks:
    - name: Wait 2 minute for Photon {{ inventory_hostname }} to boot
      ansible.builtin.pause:
        seconds: 10
