---
- hosts: all
  become: no
  connection: local
  gather_facts: False
  tasks:
    - name: Deploy OVAs for Inventory Using Photon OS
      community.vmware.vmware_deploy_ovf:
        hostname: "{{ Target.vCenter.FQDN }}"
        username: "{{ Target.vCenter.User }}"
        password: "{{ Common.Password.Physical }}" 
        validate_certs: no
        name: "{{ inventory_hostname }}" 
        datacenter: "{{ Target.vCenter.DataCenter }}"
        folder: ""
        cluster: "{{ Target.vCenter.Cluster }}"
        datastore: "{{ Target.vCenter.Datastore }}"
        disk_provisioning: thin
        networks: 
          "None": "{{ segment }}"
        ova: /Software/VMware/Photon/v3/photon-hw11-3.0-a383732.ova
        allow_duplicates: no
        power_on: yes
        fail_on_spec_warnings: yes
        wait: no
